=== DevopsCBRE01/Actividad02_XML_DTD_XSD/biblioteca.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Documento"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Documento">
      <xs:complexType>
          <xs:choice>
              <xs:element name="libro"/>
              <xs:element name="revista"/>
              <xs:element name="periodico"/>
            </xs:choice>
            <xs:attribute name="id" use="required" type="xs:string"/>
      </xs:complexType>
  </xs:element>
  <xs:simpleType name="libro">
   <xs:restriction base="xs:string">
      <xs:enumeration value="novela"/>
      <xs:enumeration value="infantil"/>
      <xs:enumeration value="didactico"/>
   </xs:restriction>
</xs:simpleType>
  <xs:element name="libro">
      <xs:complexType>
          <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="Capitulos" type="xs:string"/>
              <xs:element name="indice_de_contenido" type="xs:string"/>
              <xs:element name="sinopsis" type="xs:string"/>
            </xs:sequence>
              <xs:attribute name="tipo_clase" use="required" type="xs:string"/>
              <xs:attribute name="numero_de_paginas" use="required" type="xs:integer"/> 
      </xs:complexType>
    </xs:element>
    <xs:element name="Capitulos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="capitulo"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="capitulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contenido"/>
            </xs:sequence>
            <xs:attribute name="titulo" use="required" type="xs:string"/> 
            <xs:attribute name="numero_de_paginas" use="required" type="xs:integer"/> 
        </xs:complexType>
    </xs:element>
    <xs:element name="contenido">
        <xs:complexType>
            <xs:attribute name="enlace" use="required" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="revista">
        <xs:restriction base="xs:string">
           <xs:enumeration value="informatica"/>
           <xs:enumeration value="corazon"/>
           <xs:enumeration value="coches"/>
           <xs:enumeration value="investigacion"/>
           <xs:enumeration value="otras"/>
        </xs:restriction>
     </xs:simpleType>
    <xs:element name="revista">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tituloR" type="xs:string"/>
                <xs:element name="numero_de_revista" type="xs:integer"/>
                <xs:element name="indice" type="xs:string"/>
                <xs:element name="Secciones" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="tipo_clase" use="required" type="xs:string"/>
            <xs:attribute name="numero_de_paginas" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Secciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seccion"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="seccion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contenidoR"/>
            </xs:sequence>
            <xs:attribute name="numero_de_paginas"/>
        </xs:complexType>     
    </xs:element>
        <xs:element name="contenidoR">
            <xs:complexType>
                <xs:attribute name="enlace" use="required" type="xs:anyURI"/>
            </xs:complexType>
        </xs:element>
        <xs:simpleType name="periodico">
        <xs:restriction base="xs:string">
           <xs:enumeration value="nacional"/>
           <xs:enumeration value="internacional"/>
        </xs:restriction>
     </xs:simpleType>
   
    <xs:element name="periodico">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="indice_seccion" type="xs:string"/>
                <xs:element name="Secciones_periodico" type="xs:string"/>  
            </xs:sequence>
            <xs:attribute name="tipo_clase" use="required" type="xs:string"/>
            <xs:attribute name="fecha_publicacion" use="required" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Secciones_periodico">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seccion_periodico"/> 
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="seccion_periodico">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="articulos"/> 
            </xs:sequence>
            <xs:attribute name="tipo_seccion" type="xs:string"/>   
        </xs:complexType>
    </xs:element>
    <xs:element name="articulos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="articulo"/> 
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="articulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contenidoP"/> 
            </xs:sequence>
            <xs:attribute name="autor" type="xs:string"/>      
        </xs:complexType>
    </xs:element>
    <xs:element name="contenidoP">
        <xs:complexType>
            <xs:attribute name="enlace" use="required" type="xs:anyURI"/>
        </xs:complexType>
        </xs:element>
</xs:schema>

=== DevopsCBRE01/Actividad02_XML_DTD_XSD/Actividad02_XML+XSD/biblioteca_xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "biblioteca.xsd">
    <!--Declaración XML para el documento libro-->
    <Documento id="L0001">
        <libro tipo_clase="novela" numero_de-paginas="535">
            <titulo>Sherlock Holmes</titulo>
            <Capitulos>
                <capitulo titulo="El objeto robado" numero_de_paginas="35">
                    <contenido enlace="https://libros.metabiblioteca.org/bitstream/001/571/1/Las%20aventuras%20de%20Sherlock%20Holmes.pdf"/>
                </capitulo>
            </Capitulos>
            <indice_de_contenido>Indice</indice_de_contenido>
            <sinopsis>Las aventuras de Sherlock Holmes al ser recopiladas en una sola edición,
             pasan a ser una antología de cuentos detectivescos.
             Cuya trama se centra en un crimen o misterio que debe ser resuelto a través del ingenio de un detective protagonista,
             en este caso, Holmes con la ayuda de su fiel compañero, el Dr. Watson.
            </sinopsis>
        </libro>    
    </Documento>
    <!--Declaración XML para el documento revista-->
    <Documento id="R0001">
        <revista tipo_clase="informatica" numero_de_paginas="20">
            <tituloR>Java</tituloR>
            <numero_de_revista>1</numero_de_revista>
            <indice>Indice</indice>
            <Secciones>
                <seccion numero_de_paginas="5">
                    <contenidoR enlace="https://www.channelpartner.es/corporate/noticias/1124448047402/todas-novedades-de-java-16.1.html"/>
                </seccion>
            </Secciones>
        </revista>
        
    </Documento>
<!--Declaración XML para el documento periodico-->
    <Documento id="P0001">
        <periodico tipo_clase="nacional" fecha_publicacion="12-05-2021">
            
            <indice_seccion>Indice</indice_seccion>
            <Secciones_periodico>
                <seccion_periodico tipo_seccion="deportes">
                    <articulos>
                        <articulo autor="David López">
                             <contenidoP enlace="https://www.marca.com/ultimas-noticias.html"/> 
                        </articulo>                      
                    </articulos>
                 </seccion_periodico>
            </Secciones_periodico>           
        </periodico>
    </Documento>
</biblioteca>
